src/Entity/Images.php
<?php

namespace App\Entity;

use App\Repository\ImagesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ImagesRepository::class)
 */
class Images
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Filename;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Main;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFilename(): ?string
    {
        return $this->Filename;
    }

    public function setFilename(string $Filename): self
    {
        $this->Filename = $Filename;

        return $this;
    }

    public function getMain(): ?string
    {
        return $this->Main;
    }

    public function setMain(string $Main): self
    {
        $this->Main = $Main;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\User;
use App\Entity\Trick;
use App\Entity\Picture;
use App\Form\TrickType;
use App\Form\CommentType;
use App\Entity\Commentary;
use App\Form\PictureType;
use App\Service\FileUploader;
use App\Repository\TrickRepository;
use App\Repository\CommentaryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Session\Session;

/**
 * @method Annonces[] findBy()
 */
class HomeController extends AbstractController
{
    protected $slugger;



    public function __construct(EntityManagerInterface $em, SluggerInterface $slugger)
    {
        $this->em = $em;
        $this->slugger = $slugger;
    }
    /**
     * @var \App\Entity\Trick $tricks
     * @Route("/", name="home")
     */
    public function index(TrickRepository $trickRepository, Request $request): Response
    {


        $page = $request->query->getInt('page', 1);
        if ($page <= 0) {
            $page = 1;
        }
        $nbperpage = $this->getParameter('app.nbperpage');
        $limit = $nbperpage * $page;
        $tricks = $trickRepository->findBy([], ['createDate' => 'asc'], $limit, 0);
        $tricksCount = count($trickRepository->findAll());


        return $this->render(
            'home/home.html.twig',
            [
                'tricks' => $tricks,
                'pagesuivante' => $page + 1,
                'limit' => $limit,
                'totaltricks' => $tricksCount,
            ]
        );
    }
   

}

templates/home/_delete_form.html.twig
<form method="post" action="{{ path('app_task_delete', {'id': video.id}) }}" onsubmit="return confirm('Etes vous sur de vouloir supprimer cette video?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ video.id) }}">
    <button class="btn">Delete</button>
</form>

templates/home/_form.html.twig
{{form_start(form)}}
{{form_row(form.name)}}
{{form_row(form.content)}}
{{form_row(form.category)}}
{#<div class='container'>
	<div class='row'>
		{% for picture in trick.pictures %}
			{% if trick.pictures | length == 0 %}
				Salut
			{% else %}


				<div class="">
					<img src={{asset('Image/' ~ picture.filename)}} class="mt-4 mb-4" alt="" height="150" px width="150" px></img>
				<a href="{{path('delete_image', {'id':picture.id})}}" type="submit" class="btn btn-secondary">


					<i class="far fa-trash-alt right mb-4"></i>
					Supprimer la photo
				</a>
				{% set isMain = false %}
				{% if picture.main == 1 %}
					<i class="fas fa-star"></i>
					{% set isMain = true %}
				{% endif %}
				{% if isMain == false  %}
					<a href="{{path('main_image', {'id':picture.id})}}">
						Devenir Main</a>
				{% endif %}


			{% endif %}
		{% endfor %}
	</div>
</div>#}


{{form_row(form.pictures)}}
<button type="button" class="add_item_link" data-collection-holder-class="video">Ajouter une video</button>
<ul class="video" data-prototype="{{form_widget(form.video.vars.prototype)|e('html_attr')}}">
	{% for video in form.video %}
		<li>{{ form_row(video) }}</li>
	{% endfor %}

</ul>
<button class="btn">{{ button_label|default('Ajouter la figure') }}</button>
{#data-index="{{ form.video|length > 0 ? form.video|last.vars.name + 1 : 0 }}"#}
{{form_end(form)}}

templates/home/_formtrick.html.twig
{{form_start(form)}}
{{form_row(form.name)}}
{{form_row(form.content)}}
{{form_row(form.category)}}
{{form_row(form.pictures)}}
<button type="button" class="add_item_link" data-collection-holder-class="video">Ajouter une video</button>
<ul class="video" data-prototype="{{form_widget(form.video.vars.prototype)|e('html_attr')}}">
	{% for video in form.video %}
		<li>{{ form_row(video) }}</li>
	{% endfor %}

</ul>
<button class="btn">{{ button_label|default('Ajouter la figure') }}</button>
{#data-index="{{ form.video|length > 0 ? form.video|last.vars.name + 1 : 0 }}"#}
{{form_end(form)}}

templates/home/_formupdatetrick.html.twig
{{form_start(form)}}
{{form_row(form.name)}}
{{form_row(form.content)}}
{{form_row(form.category)}}
<div class='container'>
	<div class='row'>
		{% for picture in trick.pictures %}
			{% if trick.pictures | length == 0 %}
				
			{% else %}


				<div class="">
					<img src={{asset('Image/' ~ picture.filename)}} class="mt-4 mb-4" alt="" height="150" px width="150" px></img>
				<a href="{{path('delete_image', {'id':picture.id})}}" type="submit" class="btn btn-secondary">


					<i class="far fa-trash-alt right mb-4"></i>
					Supprimer la photo
				</a>
				{% set isMain = false %}
				{% if picture.main == 1 %}
					<i class="fas fa-star"></i>
					{% set isMain = true %}
				{% endif %}
				{% if isMain == false  %}
					<a href="{{path('main_image', {'id':picture.id})}}">
						Devenir Main</a>
				{% endif %}


			{% endif %}
		{% endfor %}
	</div>
</div>


{{form_row(form.pictures)}}
<button type="button" class="add_item_link mt-4 mb-4" data-collection-holder-class="video">Ajouter une video</button>
<ul class="video" data-prototype="{{form_widget(form.video.vars.prototype)|e('html_attr')}}">
	{% for video in form.video %}
		<li>{{ form_row(video) }}</li>
	{% endfor %}

</ul>
<button class="btn">{{ button_label|default('Ajouter la figure') }}</button>
{#data-index="{{ form.video|length > 0 ? form.video|last.vars.name + 1 : 0 }}"#}
{{form_end(form)}}

templates/home/create.html.twig
{% extends "base.html.twig"  %}
{% form_theme formTrick 'bootstrap_4_layout.html.twig' %}
{% block body %}
	<div class="col-lg-8 offset-lg-1 col-md-12">
		<div class="card  mt-5">
			<div class="card-header">
				<h3>Creer une figure</h3>
			</div>
			<div
				class="card-content mb-5">
				
								
				{{include('home/_formtrick.html.twig',{form:formTrick})}}

			</div>

		
		</div>
	</div>


{% endblock %}

templates/home/home.html.twig
{% extends "base.html.twig"  %}


{% block body %}

	<div class='home'>
		<div class='container'>
			<span class='slogan'>
				<p class='slogan-p'>Born to snowboard</p>
			</span>
			<div class='icon col-1 offset-lg-11'>
				<a href="#tricks">
					<svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="currentColor" class="bi bi-arrow-down-circle-fill" viewbox="0 0 16 16">
						<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v5.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V4.5z"/>
					</svg>
				</a>
			</div>
		</div>
	</div>
	<a name="haut"></a>
	<div class="container">
		<div class="row mt-4 mb-4">
			{% for trick in tricks %}

				<div class="  col-lg-3 col-md-12">
					<div class="card mb-4" width="200" height="200">

						<div class="card-content" width="200" height="200">
							<a href="{{path('show_figure', {'slug': trick.slug})}}" class="btn btn">
								{% if trick.pictures | length == 0 %}
									<img src={{asset('asset/lion.jpg')}} class="card-img-top" alt="">

								{% elseif trick.pictures | length == 1 %}
									<img src={{asset('Image/' ~ trick.pictures | first.filename)}} class="card-img-top" alt="">

								{% elseif trick.pictures | length > 1 %}
									{% set isMain = false %}
									{% for picture in trick.pictures %}
										{% if picture.main == 1 %}
											<img src={{asset('Image/' ~ picture.filename)}} class="card-img-top" alt="">
											{% set isMain = true %}
										{% endif %}
									{% endfor %}

									{% if isMain == false  %}
										<img src={{asset('Image/' ~ trick.pictures | first.filename)}} class="card-img-top" alt="">
									{% endif %}

								{% endif %}
							</a>
						</div>


						<div class="card-footer">
							<div class="row">
								<div class="col-8">
									<a href="{{path('show_figure', {'slug': trick.slug})}}" class="btn btn-primary">
										<h6>{{trick.name}}</h6>
									</a>
								</div>


								{% if app.user %}

									<div class="col">
										<div class="name text-right">
											<a href="{{path('update_figure', {'slug':trick.slug})}}">
												<i class="far fa-edit right"></i>
											</a>
											<a href="{{path('delete_figure', {'slug':trick.slug})}}">
												<i class="far fa-trash-alt right"></i>
											</a>
											<a name="tricks"></a>
										</div>
									</div>
								{% else %}

									<div class="col">
										<div class="name text-right">

											<a name="tricks"></a>
										</div>
									</div>
								{% endif %}
							</div>
						</div>
					</div>
				</div>

			{% endfor %}
		</div>
	</div>

	{% if totaltricks > limit %}


		<div class='container col-3 offset-lg-5'>
			<div class="row">
				<div class='sun'>


					<a href="{{path('home', {'page':pagesuivante})}}" class="btn btn-primary">
						<i class="fas fa-plus-circle fa-3x"></i>
					</a>

				</div>
			</div>

		</div>
		<div class='container col-3 offset-lg-11'>
			<a href="#haut" class="btn btn-primary">
				<i class="fas fa-arrow-up"></i>
			</a>
		</div>


	{% else %}
		<div class='container col-3 offset-lg-11'>
			<a href="#haut" class="btn btn-primary">
				<i class="fas fa-arrow-up"></i>
			</a>
		</div>

	{% endif %}


{% endblock %}

templates/home/show.html.twig
{% extends "base.html.twig" %}

{% form_theme formComment 'bootstrap_4_layout.html.twig' %}

{% block body %}
	<div class="container mt-5">
		<div class="row justify-content-center mt-5">
			<div class="col-md-10 col-md-offset-1 mt-5 mb-4">
				<div class='container'>
					<div class='row'>
						{% if trick.pictures | length == 0 %}
							<img src={{asset('asset/lion.jpg')}} class="card-img-top" alt="">

						{% elseif trick.pictures | length == 1 %}
							<img src={{asset('Image/' ~ trick.pictures | first.filename)}} class="card-img-top" alt="">

						{% elseif trick.pictures | length > 1 %}
							{% set isMain = false %}
							{% for picture in trick.pictures %}
								{% if picture.main == 1 %}
									<img src={{asset('Image/' ~ picture.filename)}} class="card-img-top" alt="">
									{% set isMain = true %}
									{{ include('_partial/_tricksbuttonupdatedelete.html.twig',{'picture':picture}) }}
								{% endif %}
							{% endfor %}

							{% if isMain == false  %}
								<img src={{asset('Image/' ~ trick.pictures | first.filename)}} class="card-img-top" alt="">
							{% endif %}
						{% endif %}

					</div>
				</div>

				<div class="card-body">
					<ul class="list-inline trick-data">
						<li class="list-inline-item">
							Par :

							{{trick.users.userName}}
						</li>
						|
						<li class="list-inline-item">
							Ajouté le
							{{trick.createdate | date('d/m/y') }}
							{% if trick.createdate == trick.updatedate %}
							</li>
						{% else %}
							(<small>Mise à jour le :
								{{trick.updatedate | date('d/m/y')}}
							</small>)
						</li>
					{% endif %}
					<li class="list-inline-item">
						Catégorie :
						{{trick.category.name}}
					</li>

					<li class="list-inline-item">
						{% if app.user %}
							<div class="col">
								<div class="name text-right">
									<a href="{{path('update_figure', {'slug':trick.slug})}}">
										<i class="far fa-edit right"></i>
									</a>
									<a href="{{path('delete_figure', {'slug':trick.slug})}}">
										<i class="far fa-trash-alt right"></i>
									</a>
									<a name="tricks"></a>
								</div>
							</div>
						{% else %}
							<div class="col">
								<div class="name text-right">

									<a name="tricks"></a>
								</div>
							</div>
						{% endif %}
					</li>
				</ul>
				<hr>

				<h4 class="card-title">
					<strong>{{trick.name}}</strong>
				</h4>
				<hr>
				<div class='nonmobile d-none d-lg-block'>
					<div class="container">
						<div class="row mt-4 mb-4">
							<div class="  col-lg-3 col-md-12">
								<div class="card mb-4" width='250' height='250'>
									<div class="card-content ">

										{% if trick.pictures | length == 0 %}
											<img src={{asset('asset/lion.jpg')}} class="card-img-top" alt="">

										{% elseif trick.pictures | length == 1 %}
											<img src={{asset('Image/' ~ trick.pictures | first.filename)}} class="card-img-top" alt="">

										{% elseif trick.pictures | length > 1 %}
											{% for picture in trick.pictures %}
												<img src={{asset('Image/' ~ picture.filename)}} class="card-img-top" alt="">
											{% endfor %}
										{% endif %}
									</div>
								</div>
							</div>
							<div class="  col-lg-3 col-md-12">
								<div class="card mb-4" width='250' height='250'>
									<div class="card-content ">
										{% for video in trick.video %}
											<iframe src={{asset(video.url)}} class="card-img-top" alt=""></iframe>
										{% endfor %}

									</div>
								</div>
							</div>

						</div>
					</div>
				</div>

				<div class='mobile d-block d-lg-none'>
					<p>
						<button class="btn btn-primary" type="button" data-bs-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
							Voir Medias
						</button>
					</p>
					<div class="collapse" id="collapseExample">
						<div class="card card-body">

							<div class="container">
								<div class="row mt-4 mb-4">
									<div class="  col-lg-3 col-md-12">
										<div class="card mb-4" width='250' height='250'>
											<div class="card-content ">

												{% if trick.pictures | length == 0 %}
													<img src={{asset('asset/lion.jpg')}} class="card-img-top" alt="">

												{% elseif trick.pictures | length == 1 %}
													<img src={{asset('Image/' ~ trick.pictures | first.filename)}} class="card-img-top" alt="">

												{% elseif trick.pictures | length > 1 %}
													{% for picture in trick.pictures %}
														<img src={{asset('Image/' ~ picture.filename)}} class="card-img-top" alt="">
													{% endfor %}
												{% endif %}

											</div>
										</div>
									</div>
									<div class="  col-lg-3 col-md-12">
								<div class="card mb-4" width='250' height='250'>
									<div class="card-content ">
										{% for video in trick.video %}
											<iframe src={{asset(video.url)}} class="card-img-top" alt=""></iframe>
										{% endfor %}

									</div>
								</div>
							</div>

								</div>

							</div>
						</div>
						<hr>
					</div>
					<h5 class="card-title">Description</h5>
					<p class="card-text text-justify">{{trick.content}}
					</p>

					<div class="col-md-12 px-0 mb-30">
						<div class="comments text-center p-3"></div>
					</div>

					<span class="comments-anchor" id="comments-block"></span>
					<div class="col-md-12 pl-0 pr-0">
						<div class="comments text-left padDiv mb-30">
							<div class="entry-comments">
								<ul class="entry-comments-list list-unstyled"></ul>
							</div>
						</div>
					</div>

				</div>


				{% if app.user %}
					<div class="col-lg-6 offset-lg-3 col-md-12">
						<div class="card  mt-5">
							<div class="card-header">
								<h3>
									Ajout d'un commentaire
								</h3>
							</div>
							<div class="card-content mb-5">
								{{ form_start(formComment) }}

								{{ form_row(formComment.content,{'attr':{'placeholder':"Ecrire un commentaire..."}}) }}
								
								{{ form_end(formComment) }}
							</div>


						</div>
					</div>
				{% else %}
					<h5>
						<i class="fas fa-exclamation-triangle"></i>
						Vous ne pouvez pas commenter si vous n'êtes pas connecté!<i class="fas fa-exclamation-triangle"></i>
					</h5>
					<a class="btn btn-success" href="{{path('app_login')}}">Connexion</a>
				{% endif %}
				<section id="commentaires" class='mt-5 mb-4'>
					{% for comment in comments %}


						<div class="comment">
							<div class="row">
								<div class="col-3 mt-5">
									{{comment.user.userName}}
									<img src={{asset('Image/' ~ comment.user.avatar)}} class="" alt="" width="50" height="50"></div>

								<div class="col mt-5">{{comment.content}}
								</div>

								<div class='col-3 mt-5'>
									<small>{{comment.date | date('d/m/y', "Europe/Paris")}}
										à
										{{comment.date | date('H:i')}}</small>
								</div>
							</div>
						</div>
					{% endfor %}
				</section>
				{% if totalComment > limit %}
					<div class='container col-3 offset-lg-5'>
						<div class="row">
							<div class='sun'>
								<a href="{{path('show_figure', {'page':pagesuivante, 'slug':trick.slug})}}" class="btn btn-primary">
									<i class="far fa-comment-dots"></i>
								</a>

							</div>
						</div>
					</div>
					{% else %}
				{% endif %}
			</div>
		</div>
	{% endblock %}

templates/home/update.html.twig
{% extends "base.html.twig"  %}
{% form_theme formUpdateTrick 'bootstrap_4_layout.html.twig' %}
{% block body %}
	<div class="col-lg-8 offset-lg-1 col-md-12">
		<div class="card  mt-5">
			<div class="card-header">
				<h3>Modifier un article</h3>
			</div>
			<div
				class="card-content mb-5">
				{#}	{{ form_start(formUpdateTrick) }}
									
													{{ form_row(formUpdateTrick.name)}}
									
													{{ form_row(formUpdateTrick.content) }}
													{{ form_row(formUpdateTrick.category) }}
													<div class='container'>
														<div class='row'>
															{% for picture in trick.pictures %}
																{% if trick.pictures | length == 0 %}
																	Salut
																{% else %}
									
									
																	<div class="">
																		<img src={{asset('Image/' ~ picture.filename)}} class="mt-4 mb-4" alt="" height="150" px width="150" px></img>
																	<a href="{{path('delete_image', {'id':picture.id})}}" type="submit" class="btn btn-secondary">
									
									
																		<i class="far fa-trash-alt right mb-4"></i>
																		Supprimer la photo
																	</a>
																	{% set isMain = false %}
																	{% if picture.main == 1 %}
																		<i class="fas fa-star"></i>
																		{% set isMain = true %}
																	{% endif %}
																	{% if isMain == false  %}
																		<a href="{{path('main_image', {'id':picture.id})}}">
																			Devenir Main</a>
																	{% endif %}
									
									
																{% endif %}
															{% endfor %}
														</div>
													</div>
									
													{{ form_row(formUpdateTrick.pictures) }}#}

				{{include('home/_formupdatetrick.html.twig',{form:formUpdateTrick,'button_label':'Mettre à jour'})}}
			</div>
		
		</div>


	{% endblock %}